default: build

build:
	npm ci
	npx vite build --base '/webui/'

ci: build

test:
	@echo "No frontend unit tests yet"

lint:
	@echo "No frontend linter configured yet"

.PHONY: default build ci test lint
