---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: StencilBox
    dir: service
    main: main.go
    binary: StencilBox
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - >
        -s -w
        -X github.com/jamesread/StencilBox/internal/buildinfo.Version={{.Version}}
        -X github.com/jamesread/StencilBox/internal/buildinfo.GitCommit={{.Commit}}
        -X github.com/jamesread/StencilBox/internal/buildinfo.BuildDate={{.Date}}

archives:
  - ids: [StencilBox]

dockers:
  - dockerfile: Dockerfile
    goarch: amd64
    use: buildx
    image_templates:
      - ghcr.io/jamesread/stencilbox:{{.Tag}}-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
      - README.md
      - templates
      - layers
      - frontend/dist
      - var/config-skel
      - var/tools

  - dockerfile: Dockerfile
    goarch: arm64
    use: buildx
    image_templates:
      - ghcr.io/jamesread/stencilbox:{{.Tag}}-arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
      - README.md
      - templates
      - layers
      - frontend/dist
      - var/config-skel
      - var/tools

docker_manifests:
  - name_template: ghcr.io/jamesread/stencilbox:{{ .Version }}
    image_templates:
      - ghcr.io/jamesread/stencilbox:{{ .Version }}-amd64
      - ghcr.io/jamesread/stencilbox:{{ .Version }}-arm64

  - name_template: ghcr.io/jamesread/stencilbox:latest
    image_templates:
      - ghcr.io/jamesread/stencilbox:{{ .Version }}-amd64
      - ghcr.io/jamesread/stencilbox:{{ .Version }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
