---
branches:
  - name: main
  - name: beta
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/git'
  - - "@semantic-release/exec"
    - publishCmd: |
        goreleaser release --clean

tagFormat: '${version}'
