---
branches:
  - main
  - v1
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/git'
  - - "@semantic-release/exec"
    - publishCmd: |
        goreleaser release --clean

tagFormat: '${version}'
