---
branches:
  - name: main
  - name: v1
    range: "1.x.x"
    prerelease: false
    channel: v1

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/git'
  - - "@semantic-release/exec"
    - publishCmd: |
        goreleaser release --clean

tagFormat: '${version}'
