SCREENSHOT_DIR := ./

updatescreenshots:
	repo-common-take-screenshot start-build http://localhost:5173/webui/build-config/My%20links%20homepage
	repo-common-take-screenshot build-complete http://localhost:5173/webui/build-config/My%20links%20homepage#build
