// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file StencilBox/clientapi/v1/clientapi.proto (package StencilBox.clientapi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file StencilBox/clientapi/v1/clientapi.proto.
 */
export const file_StencilBox_clientapi_v1_clientapi: GenFile = /*@__PURE__*/
  fileDesc("CidTdGVuY2lsQm94L2NsaWVudGFwaS92MS9jbGllbnRhcGkucHJvdG8SF1N0ZW5jaWxCb3guY2xpZW50YXBpLnYxIg0KC0luaXRSZXF1ZXN0Ih8KDEluaXRSZXNwb25zZRIPCgd2ZXJzaW9uGAEgASgJMmsKFFN0ZW5jaWxCb3hBcGlTZXJ2aWNlElMKBEluaXQSJC5TdGVuY2lsQm94LmNsaWVudGFwaS52MS5Jbml0UmVxdWVzdBolLlN0ZW5jaWxCb3guY2xpZW50YXBpLnYxLkluaXRSZXNwb25zZUJHWkVnaXRodWIuY29tL2phbWVzcmVhZC9TdGVuY2lsQm94L2dlbi9TdGVuY2lsQm94L2NsaWVudGFwaS92MTtjbGllbnRhcGliBnByb3RvMw");

/**
 * @generated from message StencilBox.clientapi.v1.InitRequest
 */
export type InitRequest = Message<"StencilBox.clientapi.v1.InitRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.InitRequest.
 * Use `create(InitRequestSchema)` to create a new message.
 */
export const InitRequestSchema: GenMessage<InitRequest> = /*@__PURE__*/
  messageDesc(file_StencilBox_clientapi_v1_clientapi, 0);

/**
 * @generated from message StencilBox.clientapi.v1.InitResponse
 */
export type InitResponse = Message<"StencilBox.clientapi.v1.InitResponse"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.InitResponse.
 * Use `create(InitResponseSchema)` to create a new message.
 */
export const InitResponseSchema: GenMessage<InitResponse> = /*@__PURE__*/
  messageDesc(file_StencilBox_clientapi_v1_clientapi, 1);

/**
 * @generated from service StencilBox.clientapi.v1.StencilBoxApiService
 */
export const StencilBoxApiService: GenService<{
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.Init
   */
  init: {
    methodKind: "unary";
    input: typeof InitRequestSchema;
    output: typeof InitResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_StencilBox_clientapi_v1_clientapi, 0);
