// @generated by protoc-gen-es v2.5.1
// @generated from file StencilBox/clientapi/v1/clientapi.proto (package StencilBox.clientapi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file StencilBox/clientapi/v1/clientapi.proto.
 */
export declare const file_StencilBox_clientapi_v1_clientapi: GenFile;

/**
 * @generated from message StencilBox.clientapi.v1.InitRequest
 */
export declare type InitRequest = Message<"StencilBox.clientapi.v1.InitRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.InitRequest.
 * Use `create(InitRequestSchema)` to create a new message.
 */
export declare const InitRequestSchema: GenMessage<InitRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.InitResponse
 */
export declare type InitResponse = Message<"StencilBox.clientapi.v1.InitResponse"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: repeated StencilBox.clientapi.v1.BuildConfig build_configs = 2;
   */
  buildConfigs: BuildConfig[];
};

/**
 * Describes the message StencilBox.clientapi.v1.InitResponse.
 * Use `create(InitResponseSchema)` to create a new message.
 */
export declare const InitResponseSchema: GenMessage<InitResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildConfig
 */
export declare type BuildConfig = Message<"StencilBox.clientapi.v1.BuildConfig"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string template = 2;
   */
  template: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildConfig.
 * Use `create(BuildConfigSchema)` to create a new message.
 */
export declare const BuildConfigSchema: GenMessage<BuildConfig>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildRequest
 */
export declare type BuildRequest = Message<"StencilBox.clientapi.v1.BuildRequest"> & {
  /**
   * @generated from field: string config_name = 1;
   */
  configName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildRequest.
 * Use `create(BuildRequestSchema)` to create a new message.
 */
export declare const BuildRequestSchema: GenMessage<BuildRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildResponse
 */
export declare type BuildResponse = Message<"StencilBox.clientapi.v1.BuildResponse"> & {
  /**
   * @generated from field: string config_name = 1;
   */
  configName: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: bool found = 3;
   */
  found: boolean;

  /**
   * @generated from field: string relative_path = 4;
   */
  relativePath: string;

  /**
   * @generated from field: bool isError = 5;
   */
  isError: boolean;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildResponse.
 * Use `create(BuildResponseSchema)` to create a new message.
 */
export declare const BuildResponseSchema: GenMessage<BuildResponse>;

/**
 * @generated from service StencilBox.clientapi.v1.StencilBoxApiService
 */
export declare const StencilBoxApiService: GenService<{
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.Init
   */
  init: {
    methodKind: "unary";
    input: typeof InitRequestSchema;
    output: typeof InitResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.StartBuild
   */
  startBuild: {
    methodKind: "unary";
    input: typeof BuildRequestSchema;
    output: typeof BuildResponseSchema;
  },
}>;
