// @generated by protoc-gen-es v2.10.2
// @generated from file StencilBox/clientapi/v1/clientapi.proto (package StencilBox.clientapi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file StencilBox/clientapi/v1/clientapi.proto.
 */
export declare const file_StencilBox_clientapi_v1_clientapi: GenFile;

/**
 * @generated from message StencilBox.clientapi.v1.InitRequest
 */
export declare type InitRequest = Message<"StencilBox.clientapi.v1.InitRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.InitRequest.
 * Use `create(InitRequestSchema)` to create a new message.
 */
export declare const InitRequestSchema: GenMessage<InitRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.InitResponse
 */
export declare type InitResponse = Message<"StencilBox.clientapi.v1.InitResponse"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.InitResponse.
 * Use `create(InitResponseSchema)` to create a new message.
 */
export declare const InitResponseSchema: GenMessage<InitResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.Template
 */
export declare type Template = Message<"StencilBox.clientapi.v1.Template"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: string status = 3;
   */
  status: string;

  /**
   * @generated from field: string documentation_url = 4;
   */
  documentationUrl: string;

  /**
   * @generated from field: repeated string build_configs = 5;
   */
  buildConfigs: string[];

  /**
   * @generated from field: string description = 6;
   */
  description: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.Template.
 * Use `create(TemplateSchema)` to create a new message.
 */
export declare const TemplateSchema: GenMessage<Template>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildConfig
 */
export declare type BuildConfig = Message<"StencilBox.clientapi.v1.BuildConfig"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string template = 2;
   */
  template: string;

  /**
   * @generated from field: string output_dir = 3;
   */
  outputDir: string;

  /**
   * @generated from field: repeated string repos = 4;
   */
  repos: string[];

  /**
   * @generated from field: map<string, string> datafiles = 5;
   */
  datafiles: { [key: string]: string };

  /**
   * @generated from field: string filename = 6;
   */
  filename: string;

  /**
   * @generated from field: string path = 7;
   */
  path: string;

  /**
   * @generated from field: string error_message = 8;
   */
  errorMessage: string;

  /**
   * @generated from field: bool in_container = 9;
   */
  inContainer: boolean;

  /**
   * @generated from field: string datafiles_path = 10;
   */
  datafilesPath: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildConfig.
 * Use `create(BuildConfigSchema)` to create a new message.
 */
export declare const BuildConfigSchema: GenMessage<BuildConfig>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildRequest
 */
export declare type BuildRequest = Message<"StencilBox.clientapi.v1.BuildRequest"> & {
  /**
   * @generated from field: string config_name = 1;
   */
  configName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildRequest.
 * Use `create(BuildRequestSchema)` to create a new message.
 */
export declare const BuildRequestSchema: GenMessage<BuildRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildUpdateResponse
 */
export declare type BuildUpdateResponse = Message<"StencilBox.clientapi.v1.BuildUpdateResponse"> & {
  /**
   * @generated from field: string config_name = 1;
   */
  configName: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: bool found = 3;
   */
  found: boolean;

  /**
   * @generated from field: string relative_path = 4;
   */
  relativePath: string;

  /**
   * @generated from field: bool is_error = 5;
   */
  isError: boolean;

  /**
   * @generated from field: string build_url_base = 6;
   */
  buildUrlBase: string;

  /**
   * @generated from field: string output_size_human_readable = 7;
   */
  outputSizeHumanReadable: string;

  /**
   * @generated from field: bool in_container = 8;
   */
  inContainer: boolean;

  /**
   * @generated from field: string base_output_dir = 9;
   */
  baseOutputDir: string;

  /**
   * @generated from field: bool is_complete = 10;
   */
  isComplete: boolean;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildUpdateResponse.
 * Use `create(BuildUpdateResponseSchema)` to create a new message.
 */
export declare const BuildUpdateResponseSchema: GenMessage<BuildUpdateResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetTemplatesRequest
 */
export declare type GetTemplatesRequest = Message<"StencilBox.clientapi.v1.GetTemplatesRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.GetTemplatesRequest.
 * Use `create(GetTemplatesRequestSchema)` to create a new message.
 */
export declare const GetTemplatesRequestSchema: GenMessage<GetTemplatesRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetTemplatesResponse
 */
export declare type GetTemplatesResponse = Message<"StencilBox.clientapi.v1.GetTemplatesResponse"> & {
  /**
   * @generated from field: repeated StencilBox.clientapi.v1.Template templates = 1;
   */
  templates: Template[];
};

/**
 * Describes the message StencilBox.clientapi.v1.GetTemplatesResponse.
 * Use `create(GetTemplatesResponseSchema)` to create a new message.
 */
export declare const GetTemplatesResponseSchema: GenMessage<GetTemplatesResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetStatusRequest
 */
export declare type GetStatusRequest = Message<"StencilBox.clientapi.v1.GetStatusRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.GetStatusRequest.
 * Use `create(GetStatusRequestSchema)` to create a new message.
 */
export declare const GetStatusRequestSchema: GenMessage<GetStatusRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetStatusResponse
 */
export declare type GetStatusResponse = Message<"StencilBox.clientapi.v1.GetStatusResponse"> & {
  /**
   * @generated from field: bool in_container = 2;
   */
  inContainer: boolean;

  /**
   * @generated from field: string templates_path = 4;
   */
  templatesPath: string;

  /**
   * @generated from field: string output_path = 5;
   */
  outputPath: string;

  /**
   * @generated from field: string build_configs_dir = 6;
   */
  buildConfigsDir: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetStatusResponse.
 * Use `create(GetStatusResponseSchema)` to create a new message.
 */
export declare const GetStatusResponseSchema: GenMessage<GetStatusResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetBuildConfigsRequest
 */
export declare type GetBuildConfigsRequest = Message<"StencilBox.clientapi.v1.GetBuildConfigsRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.GetBuildConfigsRequest.
 * Use `create(GetBuildConfigsRequestSchema)` to create a new message.
 */
export declare const GetBuildConfigsRequestSchema: GenMessage<GetBuildConfigsRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetBuildConfigsResponse
 */
export declare type GetBuildConfigsResponse = Message<"StencilBox.clientapi.v1.GetBuildConfigsResponse"> & {
  /**
   * @generated from field: repeated StencilBox.clientapi.v1.BuildConfig build_configs = 1;
   */
  buildConfigs: BuildConfig[];

  /**
   * @generated from field: bool can_git_pull = 2;
   */
  canGitPull: boolean;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetBuildConfigsResponse.
 * Use `create(GetBuildConfigsResponseSchema)` to create a new message.
 */
export declare const GetBuildConfigsResponseSchema: GenMessage<GetBuildConfigsResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetBuildConfigRequest
 */
export declare type GetBuildConfigRequest = Message<"StencilBox.clientapi.v1.GetBuildConfigRequest"> & {
  /**
   * @generated from field: string config_name = 1;
   */
  configName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetBuildConfigRequest.
 * Use `create(GetBuildConfigRequestSchema)` to create a new message.
 */
export declare const GetBuildConfigRequestSchema: GenMessage<GetBuildConfigRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetBuildConfigResponse
 */
export declare type GetBuildConfigResponse = Message<"StencilBox.clientapi.v1.GetBuildConfigResponse"> & {
  /**
   * @generated from field: StencilBox.clientapi.v1.BuildConfig build_config = 1;
   */
  buildConfig?: BuildConfig;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetBuildConfigResponse.
 * Use `create(GetBuildConfigResponseSchema)` to create a new message.
 */
export declare const GetBuildConfigResponseSchema: GenMessage<GetBuildConfigResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetTemplateRequest
 */
export declare type GetTemplateRequest = Message<"StencilBox.clientapi.v1.GetTemplateRequest"> & {
  /**
   * @generated from field: string template_name = 1;
   */
  templateName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetTemplateRequest.
 * Use `create(GetTemplateRequestSchema)` to create a new message.
 */
export declare const GetTemplateRequestSchema: GenMessage<GetTemplateRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetTemplateResponse
 */
export declare type GetTemplateResponse = Message<"StencilBox.clientapi.v1.GetTemplateResponse"> & {
  /**
   * @generated from field: StencilBox.clientapi.v1.Template template = 1;
   */
  template?: Template;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetTemplateResponse.
 * Use `create(GetTemplateResponseSchema)` to create a new message.
 */
export declare const GetTemplateResponseSchema: GenMessage<GetTemplateResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.BuildHistoryEntry
 */
export declare type BuildHistoryEntry = Message<"StencilBox.clientapi.v1.BuildHistoryEntry"> & {
  /**
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: bool is_error = 3;
   */
  isError: boolean;

  /**
   * @generated from field: string output_size_human_readable = 4;
   */
  outputSizeHumanReadable: string;

  /**
   * @generated from field: string build_url = 5;
   */
  buildUrl: string;

  /**
   * @generated from field: bool is_auto_rebuild = 6;
   */
  isAutoRebuild: boolean;
};

/**
 * Describes the message StencilBox.clientapi.v1.BuildHistoryEntry.
 * Use `create(BuildHistoryEntrySchema)` to create a new message.
 */
export declare const BuildHistoryEntrySchema: GenMessage<BuildHistoryEntry>;

/**
 * @generated from message StencilBox.clientapi.v1.GetBuildHistoryRequest
 */
export declare type GetBuildHistoryRequest = Message<"StencilBox.clientapi.v1.GetBuildHistoryRequest"> & {
  /**
   * @generated from field: string config_name = 1;
   */
  configName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetBuildHistoryRequest.
 * Use `create(GetBuildHistoryRequestSchema)` to create a new message.
 */
export declare const GetBuildHistoryRequestSchema: GenMessage<GetBuildHistoryRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetBuildHistoryResponse
 */
export declare type GetBuildHistoryResponse = Message<"StencilBox.clientapi.v1.GetBuildHistoryResponse"> & {
  /**
   * @generated from field: repeated StencilBox.clientapi.v1.BuildHistoryEntry entries = 1;
   */
  entries: BuildHistoryEntry[];
};

/**
 * Describes the message StencilBox.clientapi.v1.GetBuildHistoryResponse.
 * Use `create(GetBuildHistoryResponseSchema)` to create a new message.
 */
export declare const GetBuildHistoryResponseSchema: GenMessage<GetBuildHistoryResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetCurrentUserRequest
 */
export declare type GetCurrentUserRequest = Message<"StencilBox.clientapi.v1.GetCurrentUserRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export declare const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetCurrentUserResponse
 */
export declare type GetCurrentUserResponse = Message<"StencilBox.clientapi.v1.GetCurrentUserResponse"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: bool is_authenticated = 2;
   */
  isAuthenticated: boolean;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export declare const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GitPullRequest
 */
export declare type GitPullRequest = Message<"StencilBox.clientapi.v1.GitPullRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.GitPullRequest.
 * Use `create(GitPullRequestSchema)` to create a new message.
 */
export declare const GitPullRequestSchema: GenMessage<GitPullRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GitPullResponse
 */
export declare type GitPullResponse = Message<"StencilBox.clientapi.v1.GitPullResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GitPullResponse.
 * Use `create(GitPullResponseSchema)` to create a new message.
 */
export declare const GitPullResponseSchema: GenMessage<GitPullResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.DataFile
 */
export declare type DataFile = Message<"StencilBox.clientapi.v1.DataFile"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: string build_config_name = 3;
   */
  buildConfigName: string;

  /**
   * @generated from field: string build_config_path = 4;
   */
  buildConfigPath: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.DataFile.
 * Use `create(DataFileSchema)` to create a new message.
 */
export declare const DataFileSchema: GenMessage<DataFile>;

/**
 * @generated from message StencilBox.clientapi.v1.ListDataFilesRequest
 */
export declare type ListDataFilesRequest = Message<"StencilBox.clientapi.v1.ListDataFilesRequest"> & {
};

/**
 * Describes the message StencilBox.clientapi.v1.ListDataFilesRequest.
 * Use `create(ListDataFilesRequestSchema)` to create a new message.
 */
export declare const ListDataFilesRequestSchema: GenMessage<ListDataFilesRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.ListDataFilesResponse
 */
export declare type ListDataFilesResponse = Message<"StencilBox.clientapi.v1.ListDataFilesResponse"> & {
  /**
   * @generated from field: repeated StencilBox.clientapi.v1.DataFile data_files = 1;
   */
  dataFiles: DataFile[];

  /**
   * @generated from field: bool can_git_pull = 2;
   */
  canGitPull: boolean;
};

/**
 * Describes the message StencilBox.clientapi.v1.ListDataFilesResponse.
 * Use `create(ListDataFilesResponseSchema)` to create a new message.
 */
export declare const ListDataFilesResponseSchema: GenMessage<ListDataFilesResponse>;

/**
 * @generated from message StencilBox.clientapi.v1.GetDataFileRequest
 */
export declare type GetDataFileRequest = Message<"StencilBox.clientapi.v1.GetDataFileRequest"> & {
  /**
   * @generated from field: string build_config_name = 1;
   */
  buildConfigName: string;

  /**
   * @generated from field: string datafile_name = 2;
   */
  datafileName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetDataFileRequest.
 * Use `create(GetDataFileRequestSchema)` to create a new message.
 */
export declare const GetDataFileRequestSchema: GenMessage<GetDataFileRequest>;

/**
 * @generated from message StencilBox.clientapi.v1.GetDataFileResponse
 */
export declare type GetDataFileResponse = Message<"StencilBox.clientapi.v1.GetDataFileResponse"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: string build_config_name = 3;
   */
  buildConfigName: string;

  /**
   * @generated from field: string datafile_name = 4;
   */
  datafileName: string;
};

/**
 * Describes the message StencilBox.clientapi.v1.GetDataFileResponse.
 * Use `create(GetDataFileResponseSchema)` to create a new message.
 */
export declare const GetDataFileResponseSchema: GenMessage<GetDataFileResponse>;

/**
 * @generated from service StencilBox.clientapi.v1.StencilBoxApiService
 */
export declare const StencilBoxApiService: GenService<{
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.Init
   */
  init: {
    methodKind: "unary";
    input: typeof InitRequestSchema;
    output: typeof InitResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.StartBuild
   */
  startBuild: {
    methodKind: "server_streaming";
    input: typeof BuildRequestSchema;
    output: typeof BuildUpdateResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetTemplates
   */
  getTemplates: {
    methodKind: "unary";
    input: typeof GetTemplatesRequestSchema;
    output: typeof GetTemplatesResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetTemplate
   */
  getTemplate: {
    methodKind: "unary";
    input: typeof GetTemplateRequestSchema;
    output: typeof GetTemplateResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetStatus
   */
  getStatus: {
    methodKind: "unary";
    input: typeof GetStatusRequestSchema;
    output: typeof GetStatusResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetBuildConfigs
   */
  getBuildConfigs: {
    methodKind: "unary";
    input: typeof GetBuildConfigsRequestSchema;
    output: typeof GetBuildConfigsResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetBuildConfig
   */
  getBuildConfig: {
    methodKind: "unary";
    input: typeof GetBuildConfigRequestSchema;
    output: typeof GetBuildConfigResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetBuildHistory
   */
  getBuildHistory: {
    methodKind: "unary";
    input: typeof GetBuildHistoryRequestSchema;
    output: typeof GetBuildHistoryResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof GetCurrentUserRequestSchema;
    output: typeof GetCurrentUserResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GitPull
   */
  gitPull: {
    methodKind: "unary";
    input: typeof GitPullRequestSchema;
    output: typeof GitPullResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.ListDataFiles
   */
  listDataFiles: {
    methodKind: "unary";
    input: typeof ListDataFilesRequestSchema;
    output: typeof ListDataFilesResponseSchema;
  },
  /**
   * @generated from rpc StencilBox.clientapi.v1.StencilBoxApiService.GetDataFile
   */
  getDataFile: {
    methodKind: "unary";
    input: typeof GetDataFileRequestSchema;
    output: typeof GetDataFileResponseSchema;
  },
}>;
