= Custom Repos

StencilBox comes with a few built-in templates and a simple theme. However you may want to use a different theme, inject content into templates (via hooks), use custom icons, or even create your own templates. This is where custom repos come in.

Custom repos are simply Git repositories that contain templates, assets, or other content that you want to use in your StencilBox builds. You can host these repositories anywhere - GitHub, GitLab, Bitbucket, or even a self-hosted Git server.

To use a custom repo, you need to add it to your build config. See the build config below for an example:

[source,yaml]
----
name: My sidebar of apps

template: iframe-sidebar

outputdir: sidebar

repos:
  - url: https://github.com/homarr-labs/dashboard-icons.git
    timeout: 300 # approx 1.3gb, can take 5 minutes (300 seconds) to download

datafiles:
  links: data/sidebar-links.yaml
----

In the example above, we are adding a custom repo that contains icons for the apps we want to link to in our sidebar. The `timeout` field is optional and specifies how long (in seconds) StencilBox should wait for the repo to clone before timing out. This is useful for large repositories that may take longer to clone.

== Using repos during builds

When you add a repo in your build config, StencilBox will clone the repository to a temporary location during the build process. How these repos are used depends on the content;

* If the repo contains `body.html` or `head.html` files, these are treated as "tooks" and will be injected directly into the template at the appropriate hook locations. These can contain any valid HTML (including `<script>` tags for JavaScript, or `<style>` tags for CSS).
* If the repo contains a template, then you can reference that template in your build config by setting the `template` field to the path of the repo. eg: `repos/my-custom-repo`. 
